complete HW2
made-ml-in-prod-2022/aHadoouken pull request #2
Opened 2022-05-25 22:00 UTC by aHadoouken

- [ ] 1.Обернул модель в rest сервис на FastAPI (см. app.py), добавлен endpoint /predict (3 балла)

- [ ] 2.Написан endpoint /health, возвращает 200 если модель готова и 503 если нет (1 балл)

- [ ] 3.Написаны unit тесты для /health и /predict (см. test_app.py) (3 балла)

- [ ] 4.Написан скрипт, который отсылает запросы к серверу (см. script.py) (2 балла)

- [ ] 5.Написан dockerfile на его основе собран и запущен локально контейнер с rest сервисом. В ReadMe описаны команды для сборки (4 балл)

- [ ] 6. Образ из п.5 опубликован на https://hub.docker.com/, используя docker push (2 балла)

- [ ] 7. В ReadMe записаны команды для pull/run докера с хаба. Сервис протестирован с помощью скрипта из п.4 (1 балл)

- [ ] 8. Самооценка проведена, сумма баллов - 17 (1 балл)

2022-06-15 11:17 UTC, SVizor42 commented on online_inference/app.py
> +def health():
Return type?

2022-06-15 11:18 UTC, SVizor42 commented on online_inference/utils/utils.py
> +
+1 пустая строка

2022-06-15 11:20 UTC, SVizor42 commented on online_inference/script.py
> +from email.policy import default
Этот импорт используется?

2022-06-15 11:22 UTC, SVizor42 commented on online_inference/script.py
> +def main(data_path, model, host, port):
Типы аргументов?

2022-06-15 11:24 UTC, SVizor42 requested changes
В целом ок.

Пару моментов:
1. Вынеси зависимости для ДЗ#2 в отдельный файл, иначе совсем тяжелые докер образы получаются. Для model serving этот набор зависимостей может быть гораздо меньше, чем для обучения
2. `Dockerfile` лучше тоже перенести в `online_inference`

2022-06-22 10:52 UTC, SVizor42 approved these changes
**Сумма: 17 баллов**

Можешь сливать ветку

2022-06-22 11:41 UTC, aHadoouken commented
Я исправил таки минорные указанные ошибки. К сожалению, перенести зависимости и уменьшить докер образ не успел

2022-06-22 11:42 UTC, merged